### ISSUE TITLE
Normal bug

### ISSUE THREAD

**Issue by L-the-forgettable** [glotchalotch/Funkin-duet#1]
On 1.6.2, Selecting easy or hard does nothing, it just shoves you in to normal regardless.

**Comment by glotchalotch** [comment]
i can't seem to reproduce this. is this in story or freeplay? and is this for a custom song/week or does it happen for every song/week? i can't really think of any reason why this would happen, i never touched the difficulty selection.

**Comment by L-the-forgettable** [comment]
Free play, Currently I've tested on two different custom songs and it happens, but not with the official songs. No new weeks, no new difficulties, only the two songs it changes to normal upon selecting easy/hard. If it has nothing to do with what you have changed, then the only two possibilities that remain are A) That I am simply being an idiot in some way and have just now wasted someone's time, or B) it has to do with Modding+

**Comment by glotchalotch** [comment]
you ought to make sure that the easy and hard chart files exist in `assets/data/<song>`. looking at the code, it seems to default to normal if it can't find them

**Comment by L-the-forgettable** [comment]
Taking a closer look, it seems I was just being an idiot again. The files were in the correct folder, just two letters were swapped. Apologies for wasting your time.
