### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by L-the-forgettable** [glotchalotch/Funkin-duet#2]
Unfortunately, I am back with another bug. This time, I'm fairly certain it isn't a user error.
Lets hope I'm right with that.

Opening the editor, adding a duet char, copying the main charting to the duet char's chart, then flipping it does weird things to the duet char's charting. I cant explain it completely, but for the most part the char follows the chart intended, but when its their team's turn, they for some reason get arrows out of nowhere and only use one lane. an example is [here](https://youtu.be/IfYc2-3Kdh0), simple video uploaded to YouTube showcasing the problem on mom with her in the middle for closer observation.

Latest version (1.6.2), charting used is High.

Again, if I'm just being an idiot in some way, then i wouldent doubt it.

**Comment by glotchalotch** [comment]
sounds like i got a number wrong somewhere when the data is copied. i'll have a look at this in a little while

**Comment by glotchalotch** [comment]
this is really odd, i can't see how this could have happened. it seems like mom is mirroring the left arrows from bf's side, but i can't see why this would have happened. just so i have it right btw, mom is a duet character for sarvente correct?

can you also check the chart itself to see if those left arrows are a part of the chart or not? this is very weird indeed.

**Comment by L-the-forgettable** [comment]
Okay honestly I have no idea how this glitch behaves. reason I say this, is because I placed two duet chars into the charting, one of each that follow the primary charting, but with the sections flipped so they follow their opponent. It is extremely difficult to explain, so I [uploaded two json files](https://drive.google.com/drive/folders/1lEFebMowLVeZGnDwkviN1RLlmT-N-nUj?usp=sharing) I made, one before recording and one after, and the a video I took on my end of said charting being played, and additionally how I even managed to reach a similar position. Here's the referenced [video](https://youtu.be/hGgQ3Txp07g)

**Comment by glotchalotch** [comment]
alright i finally figured out what was wrong with this one. turns out that i made a typo of a single character while figuring out how async notes should be played. 
```
if ((SONG.notes[Std.int(curStep / stepsPerSection)].mustHitSection && note[1] > 4)
|| (!SONG.notes[Std.int(curStep / stepsPerSection)].mustHitSection && note[1] < 4))
forBF = false;
```
vs
```
if ((SONG.notes[Std.int(curStep / stepsPerSection)].mustHitSection && note[1] >= 4)
|| (!SONG.notes[Std.int(curStep / stepsPerSection)].mustHitSection && note[1] < 4))
forBF = false;
```

that > instead of >= meant that note direction 4 (aka a left note on the right side of the chart editor) was played on the wrong side under a specific set of circumstances. this didn't have anything to do with swapping sections, which ended up being a little bit of a red herring as i was looking for it. good challenge for me though! tiny logic errors like these are really tough.
