### ISSUE TITLE
Issue number 4

### ISSUE THREAD

**Issue by L-the-forgettable** [glotchalotch/Funkin-duet#4]
Version 1.6.2, Windows 64 Bit. (Yes i have yet to update the engine. i have plans on it, but i must finish an update to something i'm working on before i can.)

I'm not sure if this is a bug or not, but the "Sync" option for duet chars doesn't actually appear to work. I have a feeling its supposed to give an alternative to copying all the charting to the duet chars, but as stated above its not really working.

Not 100% sure if its still a bug on 6.3, but i have a feeling it might still be there.

I would have mentioned sooner, but found that simply copying all the charting over was a valid alternative.

**Comment by glotchalotch** [comment]
it doesn't activate automatically, you have to activate it on a note. check out [the original video tutorial](https://youtu.be/FHvePQe9rK8) to see how to use it

**Comment by L-the-forgettable** [comment]
Aha, apologies!
